#!/bin/bash

function setup_vim() {
  ln -sf ~/.files/.vimrc ~/.vimrc
  mkdir -p ~/.vim/colors
  mkdir -p ~/.vim/swapfiles
  ln -sf ~/.files/.vim/colors/icahoon.vim ~/.vim/colors/icahoon.vim
}

function setup_vundle() {
  if [ -d ~/.vim/bundle/Vundle.vim ]; then
    return
  fi
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
}

function setup_bash() {
  local i
  for i in .bash_profile .bashrc .bash_logout; do
    ln -sf ~/.files/$i ~/$i
  done
  mkdir -p ~/.rc.d
  mkdir -p ~/.profile.d
  for i in ~/.files/.rc.d/*.sh; do
    ln -sf $i ~/.rc.d
  done
  for i in ~/.files/.profile.d/*.sh; do
    ln -sf $i ~/.profile.d
  done
}

function setup_name() {
  if [ "$NAME" != "" ]; then
    return
  fi
  local name=""
  local email=""
  echo -en "Full name:\t"; read name
  echo -en "Email address:\t"; read email
  echo "export NAME=\"$name\"" > ~/.profile.d/name.sh
  echo "export EMAIL=\"$email\"" >> ~/.profile.d/name.sh
  source ~/.profile.d/name.sh
}

function setup_ssh() {
  if [ ! -d ~/.ssh ]; then
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
  fi
  #ssh-keygen -t rsa -b 4096 -C $EMAIL
  if [ ! -f ~/.profile.d/_ssh_keys.sh ]; then
    echo "export ssh_keys=\"id_rsa\"" > ~/.profile.d/_ssh_keys.sh
  fi
}

function setup_bin() {
  if [ ! -d ~/bin ]; then
    mkdir -p ~/bin
  fi
  local i
  for i in ~/.files/bin/*; do
    ln -sf $i ~/bin
  done
}

function setup_fonts() {
  mkdir -p ~/.fonts
  local i
  for i in ~/.files/.fonts/*; do
    ln -sf $i ~/.fonts
  done
  if type fc-cache &>/dev/null; then
    fc-cache -v
  fi
}

function setup_tmux() {
  mkdir -p ~/.tmux
  ln -sf ~/.files/.tmux.conf ~/.tmux.conf
}

function setup_go() {
  vim +GoInstallBinaries +qall
}

function setup_git() {
  if [ "$(git config --get user.email)" != "" ]; then
    return
  fi
  rm -f ~/.gitconfig
  git config --global user.name "$NAME"
  git config --global user.email "$EMAIL"
  git config --global push.default "tracking"
  git config --global color.ui "auto"
  git config --global core.editor "vim"
  git config --global core.autocrlf "false"
  git config --global core.filemode "false"
  git config --global merge.tool "vimdiff"

  git config --global core.excludesfile ~/.gitignore_global
  ln -sf ~/.files/.gitignore_global ~/.gitignore_global
}

function setup_terminator() {
  mkdir -p ~/.config/terminator
  ln -sf ~/.files/.config/terminator/config ~/.config/terminator/config
  mkdir -p ~/.gnome/apps
  ln -sf ~/.files/.gnome/apps/terminator.desktop ~/.gnome/apps/terminator.desktop
}

function setup_dev() {
  mkdir -p ~/.projects
  ln -sf ~/.files/.projects ~/.projects/icahoon@gmail.com
}

function main() {
  setup_vim
  setup_vundle
  setup_bash
  setup_name
  setup_bin
  setup_fonts
  setup_tmux
  setup_go
  setup_git
  setup_terminator
  setup_dev
}

main "$@"
